/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etla.mod.etl.form;

import etla.mod.SModConsts;
import etla.mod.etl.db.SDbSalesAgent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import sa.lib.SLibConsts;
import sa.lib.SLibUtils;
import sa.lib.db.SDbRegistry;
import sa.lib.gui.SGuiClient;
import sa.lib.gui.SGuiConsts;
import sa.lib.gui.SGuiUtils;
import sa.lib.gui.SGuiValidation;
import sa.lib.gui.bean.SBeanForm;

/**
 *
 * @author Sergio Flores
 */
public class SFormSalesAgent extends SBeanForm implements ActionListener {
    
    private SDbSalesAgent moRegistry;
    
    /**
     * Creates new form SFormSalesAgent
     * @param client
     * @param title
     */
    public SFormSalesAgent(SGuiClient client, String title) {
        setFormSettings(client, SGuiConsts.BEAN_FORM_EDIT, SModConsts.AU_SAL_AGT, SLibConsts.UNDEFINED, title);
        initComponents();
        initComponentsCustom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlCode = new javax.swing.JLabel();
        jtfCode = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jlName = new javax.swing.JLabel();
        jtfName = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jlDesSalesAgentId = new javax.swing.JLabel();
        moIntDesSalesAgentId = new sa.lib.gui.bean.SBeanFieldInteger();
        jbEditDesSalesAgentId = new javax.swing.JButton();
        jlSiie = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del registro:"));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel2.setLayout(new java.awt.GridLayout(3, 1, 0, 5));

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlCode.setText("Código:");
        jlCode.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel3.add(jlCode);

        jtfCode.setEditable(false);
        jtfCode.setFocusable(false);
        jtfCode.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel3.add(jtfCode);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlName.setText("Nombre:*");
        jlName.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel4.add(jlName);

        jtfName.setEditable(false);
        jtfName.setFocusable(false);
        jtfName.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel4.add(jtfName);

        jPanel2.add(jPanel4);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlDesSalesAgentId.setText("ID asoc. negocios:*");
        jlDesSalesAgentId.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel12.add(jlDesSalesAgentId);
        jPanel12.add(moIntDesSalesAgentId);

        jbEditDesSalesAgentId.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sa/lib/img/cmd_std_edit.gif"))); // NOI18N
        jbEditDesSalesAgentId.setToolTipText("Modificar");
        jbEditDesSalesAgentId.setPreferredSize(new java.awt.Dimension(23, 23));
        jPanel12.add(jbEditDesSalesAgentId);

        jlSiie.setForeground(java.awt.Color.gray);
        jlSiie.setText("(Primary Key SIIE)");
        jlSiie.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel12.add(jlSiie);

        jPanel2.add(jPanel12);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel5.setLayout(new java.awt.BorderLayout(5, 0));
        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jbEditDesSalesAgentId;
    private javax.swing.JLabel jlCode;
    private javax.swing.JLabel jlDesSalesAgentId;
    private javax.swing.JLabel jlName;
    private javax.swing.JLabel jlSiie;
    private javax.swing.JTextField jtfCode;
    private javax.swing.JTextField jtfName;
    private sa.lib.gui.bean.SBeanFieldInteger moIntDesSalesAgentId;
    // End of variables declaration//GEN-END:variables

    /*
     * Private methods
     */
    
    private void initComponentsCustom() {
        SGuiUtils.setWindowBounds(this, 480, 300);
        
        moIntDesSalesAgentId.setIntegerSettings(SGuiUtils.getLabelName(jlDesSalesAgentId), SGuiConsts.GUI_TYPE_INT_RAW, true);
        
        moFields.addField(moIntDesSalesAgentId);
        
        moFields.setFormButton(jbSave);
    }
    
    private void enableEditDesSalesAgentId(boolean enable) {
        moIntDesSalesAgentId.setEditable(enable);
        jbEditDesSalesAgentId.setEnabled(!enable);
    }
    
    private void actionEditDesSalesAgentId() {
        enableEditDesSalesAgentId(true);
        moIntDesSalesAgentId.requestFocus();
    }
    
    /*
     * Public methods
     */
    
    /*
     * Overriden methods
     */
    
    @Override
    public void addAllListeners() {
        jbEditDesSalesAgentId.addActionListener(this);
    }

    @Override
    public void removeAllListeners() {
        jbEditDesSalesAgentId.removeActionListener(this);
    }

    @Override
    public void reloadCatalogues() {
        
    }

    @Override
    public void setRegistry(SDbRegistry registry) throws Exception {
        moRegistry = (SDbSalesAgent) registry;

        mnFormResult = SLibConsts.UNDEFINED;
        mbFirstActivation = true;

        removeAllListeners();
        reloadCatalogues();

        if (moRegistry.isRegistryNew()) {
            jtfRegistryKey.setText("");
        }
        else {
            jtfRegistryKey.setText(SLibUtils.textKey(moRegistry.getPrimaryKey()));
        }

        jtfCode.setText(moRegistry.getCode());
        jtfCode.setCaretPosition(0);
        jtfName.setText(moRegistry.getName());
        jtfName.setCaretPosition(0);
        moIntDesSalesAgentId.setValue(moRegistry.getDesSalesAgentId());

        setFormEditable(true);
        
        enableEditDesSalesAgentId(false);
        
        if (moRegistry.isRegistryNew()) {
        }
        else {
        }
        
        addAllListeners();
    }

    @Override
    public SDbSalesAgent getRegistry() throws Exception {
        SDbSalesAgent registry = moRegistry.clone();

        if (registry.isRegistryNew()) {}

        registry.setDesSalesAgentId(moIntDesSalesAgentId.getValue());

        return registry;
    }

    @Override
    public SGuiValidation validateForm() {
        SGuiValidation validation = moFields.validateFields();
        
        return validation;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() instanceof JButton) {
            JButton button = (JButton) e.getSource();
            
            if (button == jbEditDesSalesAgentId) {
                actionEditDesSalesAgentId();
            }
        }
    }
}
