/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etla.mod.sms.form;

import etla.mod.SModConsts;
import etla.mod.sms.db.SDbForkliftDriver;
import sa.lib.SLibConsts;
import sa.lib.SLibUtils;
import sa.lib.db.SDbRegistry;
import sa.lib.gui.SGuiClient;
import sa.lib.gui.SGuiConsts;
import sa.lib.gui.SGuiUtils;
import sa.lib.gui.SGuiValidation;
import sa.lib.gui.bean.SBeanForm;

/**
 *
 * @author Isabel Servín
 */
public class SFormForkliftDriver extends SBeanForm {
    
    private SDbForkliftDriver moRegistry;
    
    /**
     * Creates new form SFormCustomer
     * @param client
     * @param title
     */
    public SFormForkliftDriver(SGuiClient client, String title) {
        setFormSettings(client, SGuiConsts.BEAN_FORM_EDIT, SModConsts.SU_FORKLIFT_DRV, SLibConsts.UNDEFINED, title);
        initComponents();
        initComponentsCustom();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jlCode = new javax.swing.JLabel();
        moTextCode = new sa.lib.gui.bean.SBeanFieldText();
        jPanel8 = new javax.swing.JPanel();
        jlLastname = new javax.swing.JLabel();
        moTextLastname = new sa.lib.gui.bean.SBeanFieldText();
        jPanel4 = new javax.swing.JPanel();
        jlForename = new javax.swing.JLabel();
        moTextForename = new sa.lib.gui.bean.SBeanFieldText();
        jPanel5 = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del registro:"));
        jPanel1.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel2.setLayout(new java.awt.GridLayout(7, 1, 0, 5));

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlCode.setText("Núm de empleado:*");
        jlCode.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel3.add(jlCode);
        jPanel3.add(moTextCode);

        jPanel2.add(jPanel3);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlLastname.setText("Apellido:*");
        jlLastname.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel8.add(jlLastname);

        moTextLastname.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel8.add(moTextLastname);

        jPanel2.add(jPanel8);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        jlForename.setText("Nombre:*");
        jlForename.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel4.add(jlForename);

        moTextForename.setPreferredSize(new java.awt.Dimension(300, 23));
        jPanel4.add(moTextForename);

        jPanel2.add(jPanel4);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel5.setLayout(new java.awt.BorderLayout(5, 0));
        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel jlCode;
    private javax.swing.JLabel jlForename;
    private javax.swing.JLabel jlLastname;
    private sa.lib.gui.bean.SBeanFieldText moTextCode;
    private sa.lib.gui.bean.SBeanFieldText moTextForename;
    private sa.lib.gui.bean.SBeanFieldText moTextLastname;
    // End of variables declaration//GEN-END:variables

    /*
     * Private methods
     */
    
    private void initComponentsCustom() {              
        SGuiUtils.setWindowBounds(this, 480, 300);
        
        moTextCode.setTextSettings(SGuiUtils.getLabelName(jlCode), 10);
        moTextForename.setTextSettings(SGuiUtils.getLabelName(jlForename), 100);
        moTextLastname.setTextSettings(SGuiUtils.getLabelName(jlLastname), 100);
        
        moFields.addField(moTextCode);
        moFields.addField(moTextForename);
        moFields.addField(moTextLastname);
        
        moFields.setFormButton(jbSave);
    }    
    
    
    /*
     * Public methods
     */
    
    /*
     * Overriden methods
     */
    
    @Override
    public void addAllListeners() {
    }

    @Override
    public void removeAllListeners() {
    }

    @Override
    public void reloadCatalogues() {
        
    }

    @Override
    public void setRegistry(SDbRegistry registry) throws Exception {
        moRegistry = (SDbForkliftDriver) registry;

        mnFormResult = SLibConsts.UNDEFINED;
        mbFirstActivation = true;

        removeAllListeners();
        reloadCatalogues();

        if (moRegistry.isRegistryNew()) {
            jtfRegistryKey.setText("");
        }
        else {
            jtfRegistryKey.setText(SLibUtils.textKey(moRegistry.getPrimaryKey()));
        }

        moTextCode.setText(moRegistry.getCode());
        moTextForename.setText(moRegistry.getForename());
        moTextLastname.setText(moRegistry.getLastname());
        
        setFormEditable(true);
        
    }

    @Override
    public SDbForkliftDriver getRegistry() throws Exception {
        SDbForkliftDriver registry = (SDbForkliftDriver) moRegistry.clone();

        if (registry.isRegistryNew()) {}

        //registry.setPkForkliftDriver(...);
        registry.setCode(moTextCode.getValue());
        registry.setLastname(moTextLastname.getValue());
        registry.setForename(moTextForename.getValue());
        registry.setName(moTextLastname.getValue() + ", " + moTextForename.getValue());
        //registry.setDeleted(...);
        //registry.setFkUserInsertId(...);
        //registry.setFkUserUpdateId(...);
        //registry.setTsUserInsert(...);
        //registry.setTsUserUpdate(...);

        return registry;
    }

    @Override
    public SGuiValidation validateForm() {
        SGuiValidation validation = moFields.validateFields();
        
        return validation;
    }
    
}
